name: mlchem
channels:
  - conda-forge
  - dglteam
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - numpy=1.26
  - pandas
  - scikit-learn
  - xgboost
  - catboost
  - lightgbm
  - optuna
  - joblib
  - seaborn
  - plotly
  - ipykernel
  - notebook
  - mols2grid
  - rdkit
  - molfeat
  - dglteam::dgl<=2.0
  - dgllife
  - mordredcommunity
  - pip
  - pip:
      - epam.indigo