name: chem
channels:
  - conda-forge
  - pytorch
  - nvidia
  - rapidsai
dependencies:
  - python=3.10
  # ml
  - numpy<=1.26
  - pandas
  - rapids=24.08
  - scikit-learn
  - xgboost
  - catboost
  - lightgbm
  - optuna
  - joblib
  - seaborn
  - plotly
  - ipykernel
  - notebook
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.8
  - transformers
  # chem
  - mols2grid
  - rdkit
  - datamol
  - molfeat
  - dglteam::dgl<=2.0
  - dgllife
  - mordredcommunity
#  - tmap::tmap
  - pip
  - pip:
      - Auto3D
      - epam.indigo