name: chem
channels:
  - conda-forge
  - pytorch
  - nvidia
  - rapidsai
dependencies:
  - python=3.10
  # ml
  - numpy<2.0
  - mkl=2024.0
  - python-dotenv
  - pandas
  - rapids
  - scikit-learn
  - xgboost
  - catboost
  - lightgbm
  - optuna
  - joblib
  - seaborn
  - plotly
  - ipykernel
  - notebook
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.8
  - transformers
  - autogluon
  - ray-tune >=2.6.3,<2.7
  - ray-default >=2.6.3,<2.7
  # chem
  - mols2grid
  - rdkit
  - datamol
  - molfeat
  - dglteam::dgl<=2.0
  - dgllife
  - mordredcommunity
#  - tmap::tmap
  - pip
  - pip:
      - pip-system-certs
      - Auto3D
      - epam.indigo